mqtt:
  broker: "broker.emqx.io"
  port: 1883
  client_id1: "Radar"
  client_id2: "Camera"
  show_log: False
  compressed_output: True # for debugging/demo - send compressed data to console
Files:
  radar_data_file: ./data/radardata.json
  video_file: ./data/camdata.avi
CameraOutput:
  fps: 1 # fps for image output step size
  frame_start: 50 # which frame to start program at
  frame_skip: 3 # show every nth frame
  continuous_frame_mode: True # if True, will update display frames automatically, else waits for user key input
