mqtt:
  broker: "127.0.0.1" # alt web broker: "broker.emqx.io"
  port: 1883
  client_id1: "Radar"
  client_id2: "Camera"
  show_log: False
  compressed_output: True # for debugging/demo - send compressed data to console
Files:
  radar_data_file: ./data/radardata.json
  video_file: ./data/camdata.avi
CameraOutput:
  fps: 1 # fps for image output step size
  frame_start: 0 # which frame to start program at
  frame_skip: 1 # show every nth frame
  continuous_frame_mode: True # if True, will update display frames automatically, else waits for user key input
write_log: False # write log file

LiveData:
  radar:
    topic: "data/liveradar"
    qos: 0
    client_id: "LIVE RADAR"
    # radar 1:
    CLIport: "COM4"
    DataPort: "COM3"
    # radar 2:
    CLIport2: "COM6"
    DataPort2: "COM5"
  camera:
    width: 640
    height: 480
    fps: 20 # capped at 9fps for 1280x720, 5fps for 1920x1080, 28 fps for 640x480