mqtt:
  broker: "mqtt.eclipseprojects.io" # alt server, use module connection now
  port: None 
  client_id1: "Radar"
  client_id2: "Camera"
  show_log: False
  compressed_output: True # for debugging/demo - send compressed data to console
Files:
  radar_data_file: ./data/radardata.json
  video_file: ./data/camdata.avi
